package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with absolute id = 'ASecondaryNodeProject_WithMetaruner'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id = AbsoluteId("ASecondaryNodeProject_WithMetaruner")
    name = "With metaruner"
    paused = true

    steps {
        step {
            name = "metarun"
            type = "meta"
            executionMode = BuildStep.ExecutionMode.DEFAULT
        }
        step {
            type = "ASecondaryNodeProject_ConfigFromMainNodeCopiedOTheSecondNode"
            executionMode = BuildStep.ExecutionMode.DEFAULT
        }
    }
}))

