package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.schedule
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with absolute id = 'ASecondaryNodeProject_ConfigFromMainNode'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id = AbsoluteId("ASecondaryNodeProject_ConfigFromMainNode")
    name = "Config from main node"
    paused = true

    params {
        param("2", "2")
    }

    vcs {
        root(AbsoluteId("ASecondaryNodeProject_MainConfigVcsTests"), "+:folderC => .")
    }

    triggers {
        schedule {
            branchFilter = ""
            triggerBuild = onWatchedBuildChange {
                buildType = "id1_2_3_Xxxxx"
            }
        }
    }
}))

