package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with absolute id = 'ASecondaryNodeProject_ConfigFromMainNodeCopiedOTheSecondNode'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id = AbsoluteId("ASecondaryNodeProject_ConfigFromMainNodeCopiedOTheSecondNode")
    name = "Config from main node copied o the second node"
    paused = true

    vcs {
        root(AbsoluteId("ASecondaryNodeProject_MainConfigVcsTests"))
    }

    steps {
        script {
            name = "Secondary"
            scriptContent = "echo main111"
        }
        script {
            name = "xxxxx"
            scriptContent = "secondt"
        }
        script {
            scriptContent = "echo main"
        }
        script {
            scriptContent = "call test.cmd"
        }
    }
}))

