package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.schedule
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'ConfigFromMainNode'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("ConfigFromMainNode")) {
    check(paused == false) {
        "Unexpected paused: '$paused'"
    }
    paused = true

    params {
        add {
            param("2", "2")
        }
    }

    vcs {
        expectEntry(RelativeId("MainConfigVcsTests"))
        root(RelativeId("MainConfigVcsTests"), "+:folderC => .")
    }

    triggers {
        add {
            schedule {
                branchFilter = ""
                triggerBuild = onWatchedBuildChange {
                    buildType = "id1_2_3_Xxxxx"
                }
            }
        }
    }
}
