package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.projectFeatures.ProjectReportTab
import jetbrains.buildServer.configs.kotlin.v2019_2.projectFeatures.projectReportTab
import jetbrains.buildServer.configs.kotlin.v2019_2.projectFeatures.youtrack
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a root project
in the project with absolute id = DslContext.parentProjectId, and delete the patch script.
*/
create(DslContext.parentProjectId, Project({
    archived = true

    features {
        feature {
            id = "PROJECT_EXT_102"
            type = "IssueTracker"
            param("secure:password", "")
            param("name", "iyanke/tests")
            param("pattern", """#(\d+)""")
            param("authType", "accesstoken")
            param("repository", "https://github.com/iyanke/tests")
            param("type", "GithubIssues")
            param("secure:accessToken", "credentialsJSON:0a33f2ad-5f87-44fa-ba1c-aa334149e7a5")
            param("username", "")
        }
        youtrack {
            id = "PROJECT_EXT_105"
            displayName = "YouTrack"
            host = "http://unit-1413:8080"
            userName = "admin"
            password = "credentialsJSON:baf7ea77-77fb-4c6e-802e-724ad0df4609"
            projectExtIds = "DEMO"
            accessToken = ""
            param("authType", "loginpassword")
        }
        projectReportTab {
            id = "PROJECT_EXT_80"
            title = "vccccccc"
            startPage = "index.html"
            buildType = "ASecondaryNodeProject_ConfigFromMainNode"
            sourceBuildRule = ProjectReportTab.SourceBuildRule.LAST_SUCCESSFUL
        }
    }

    cleanup {
        keepRule {
            id = "KEEP_RULE_83"
            keepAtLeast = allBuilds()
            dataToKeep = statisticsOnly()
            applyPerEachBranch = true
            preserveArtifactsDependencies = true
        }
    }
}))

